server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  devtools:
    restart:
      enabled: true
  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      location: C:/Users/User/Desktop/file
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Book?serverTimezone=Asia/Seoul
    username: seo
    password: seo1234

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 610950748174-p213ppi7l5q9tdrc52tkee2qga9g22bo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
                
                
                